config:
  target: 'http://localhost:5002'
  phases:
    - duration: 60
      arrivalRate: 3
      name: Warm up
  payload:
    path: 'id-password.csv'
    fields:
      - 'email'
      - 'password'

scenarios:
  - name: 'login'
    flow:
      - post:
          url: '/auth/login'
          json:
            email: '{{ email }}'
            password: '{{ password }}'
          capture:
            - json: $.accesstoken
              as: accesstoken # 토큰을 accesstoken 변수에 저장
      - get:
          url: '/budgets?month=2023-11&total=2000000'
          headers:
            authorization: 'Bearer {{ accesstoken }}'
      - post:
          url: '/budgets'
          headers:
            authorization: 'Bearer {{ accesstoken }}'
